Initial creation of the Envoy AI Gateway Site
envoyproxy/ai-gateway pull request #41
Opened 2024-12-12 04:14 UTC by missBerg

- Simple landing page
- Links to get involved in community
- Basis for future Docs
- Blog setup, and a copy of the original announcement post from CNCF blog

We will need to set up the build and publish to github pages, and I've got the domain envoyaigateway.io for us to use.

2024-12-12 15:51 UTC, mathetake requested changes
Remove `node_modules`? It's going to explode the repository.
Also Could you remove .DS_Store?

2024-12-12 15:51 UTC, mathetake commented
after that let's setup a GitHub actions workflow that ensures it's buildable

2024-12-12 21:02 UTC, mathetake commented on .gitignore
> -/site/node_modules
the entire `node_modules` should be ignored, there's no reason to retain the entire copies of dependencies checked in the repo here

2024-12-17 02:03 UTC, missBerg commented
Got myself into a mess with unsigned commits, so I raised a new PR https://github.com/envoyproxy/ai-gateway/pull/46

2024-12-17 02:03 UTC, closed without merging